spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nacos_config?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:12366

server:
  port: 9988
#  servlet:
#    context-path: /order-service

feign:
  client:
    config:
      default:
        loggerLevel: FULL

